In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"E:\project_dv\paper1\mmc2.xlsx", sheet_name="Raw Data")

In [4]:
psqi_related_columns = df.columns[57:76].tolist()

df_psqi = df[psqi_related_columns].copy()

#df['2. How long (in minutes) has it taken you to fall asleep each night?'].unique()

In [6]:
### Column 1

df_psqi.head()

,1. When I am usually gone to bed?,2. How long (in minutes) has it taken you to fall asleep each night?,3. When have you usually gotten up in the morning?,4. How many hours of actual sleep do you get at night?,5. How many hours were you in bed?,"6. In last 30 days, How many times, I cannot get to sleep within 30 minutes?","7. In last 30 days, How many times, I wake up in the middle of the night or early morning?","8. In last 30 days, How many times, I had to get up to use the bathroom?","9. In last 30 days, How many times, I cannot breathe comfortably?","10. In last 30 days, How many times, I cough or snore loudly?","11. In last 30 days, How many times, I feel too cold?","12. In last 30 days, How many times, I feel too hot?","13. In last 30 days, How many times, I saw bad dreams?","14. In last 30 days, How many times, I have pain during sleep?","15. In last 30 days, How many times, I having trouble sleeping for any other reason?","16. In last 30 days, In last month, have you take medicines for sleep?","17. In last month, how many times you cannot sleep due to any program or other important case?","18. In last month, how many times you face problems to maintain program or other important case?","19. During the past month, how would you rate your sleep quality overall?"
0,12.01 AM to 2.00 AM,Within 15 minutes,After 9.00 AM,7-8 hours,8-10 hours,Once or twice a week,Not during last month,Less then once a week,Not during last month,Not during last month,Less then once a week,Not during last month,Not during last month,Not during last month,Less then once a week,Not during last month,Less then once a week,Less then once a week,Farely good
1,10.01 PM to 12.00 AM,16-30,After 9.00 AM,Less than 4 hours,More than 10 hours,Three or more in week,Not during last month,Three or more in week,Less then once a week,Less then once a week,Less then once a week,Three or more in week,Less then once a week,Not during last month,Not during last month,Less then once a week,Less then once a week,Less then once a week,Very bad
2,2.01 AM to 5.00 AM,31-60,7.01 AM to 9.00 AM,Less than 4 hours,8-10 hours,Three or more in week,Three or more in week,Less then once a week,Less then once a week,Not during last month,Not during last month,Less then once a week,Less then once a week,Three or more in week,Three or more in week,Not during last month,Three or more in week,Once or twice a week,Very bad
3,10.01 PM to 12.00 AM,Within 15 minutes,5.01 AM to 7.00 AM,4-6 hours,5-7 hours,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Farely good
4,2.01 AM to 5.00 AM,16-30,After 9.00 AM,4-6 hours,5-7 hours,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Not during last month,Less then once a week,Less then once a week,Less then once a week,Less then once a week,Less then once a week,Farely good

These match up with standard PSQI components:


PSQI Component	Related Columns You Have
1. Sleep Latency	2, 6
2. Sleep Duration	4
3. Habitual Sleep Efficiency	4, 5
4. Sleep Disturbances	7–15
5. Use of Sleep Medication	16
6. Daytime Dysfunction	17, 18
7. Subjective Sleep Quality	19

In [7]:
# Example categories to ordinal mapping
q2_column = psqi_related_columns[1]  # Index 1 in your PSQI columns list

# Clean and standardize
df_psqi[q2_column] = df_psqi[q2_column].str.strip().str.lower()

# Define ordinal mapping for Q2 categories
q2_mapping = {
    '≤ 15 minutes': 0,
    'less than 15 minutes': 0,
    '15 minutes': 0,
    '16-30 minutes': 1,
    '16 – 30 minutes': 1,
    'about 20 minutes': 1,
    '31-60 minutes': 2,
    'more than 30 minutes': 2,
    '> 60 minutes': 3,
    'more than 1 hour': 3,
    'more than 60 minutes': 3
}

# Apply ordinal encoding
df_psqi['Q2_score'] = df_psqi[q2_column].map(q2_mapping)

# Handle any unmapped values (optional)
df_psqi['Q2_score'] = df_psqi['Q2_score'].fillna(0)  # or np.nan if you want to keep missing

# Check results
print(df_psqi[[q2_column, 'Q2_score']].head())

  2. How long (in minutes) has it taken you to fall asleep each night?  \
0                                  within 15 minutes
1                                              16-30
2                                              31-60
3                                  within 15 minutes
4                                              16-30

   Q2_score
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0

### Encoding Q6

In [8]:
# Q6 column
q6_column = psqi_related_columns[5]  # Index 5 in your PSQI columns list

# Clean Q6 values
df_psqi[q6_column] = df_psqi[q6_column].str.strip().str.lower()

# Define ordinal mapping for Q6
q6_mapping = {
    'not during the past month': 0,
    'less than once a week': 1,
    'once or twice a week': 2,
    'three or more times a week': 3
}

# Apply ordinal encoding
df_psqi['Q6_score'] = df_psqi[q6_column].map(q6_mapping)

# Handle unmapped values
df_psqi['Q6_score'] = df_psqi['Q6_score'].fillna(0)  # or np.nan if needed

# Check results
print(df_psqi[[q6_column, 'Q6_score']].head())

  6. In last 30 days, How many times, I cannot get to sleep within 30 minutes?  \
0                               once or twice a week
1                              three or more in week
2                              three or more in week
3                              not during last month
4                              not during last month

   Q6_score
0       2.0
1       0.0
2       0.0
3       0.0
4       0.0

In [9]:
# Combine Q2 and Q6 scores
df_psqi['C2_sum'] = df_psqi['Q2_score'] + df_psqi['Q6_score']

# Map sum to Component 2 score
def component2_score(total):
    if total == 0:
        return 0
    elif 1 <= total <= 2:
        return 1
    elif 3 <= total <= 4:
        return 2
    else:
        return 3

df_psqi['C2'] = df_psqi['C2_sum'].apply(component2_score)

# Check results
print(df_psqi[['Q2_score', 'Q6_score', 'C2_sum', 'C2']].head())

   Q2_score  Q6_score  C2_sum  C2
0       0.0       2.0     2.0   1
1       0.0       0.0     0.0   0
2       0.0       0.0     0.0   0
3       0.0       0.0     0.0   0
4       0.0       0.0     0.0   0

### Sleep Duration

In [17]:
# Q4 column
q4_column = psqi_related_columns[3]  # Index 3 in your PSQI columns list

# Clean values
df_psqi[q4_column] = df_psqi[q4_column].str.strip().str.lower()

# Map Q4 to numeric values for efficiency calculation
q4_numeric_mapping = {
    'more than 8 hours': 8.5,
    '7-8 hours': 7.5,
    '4-6 hours': 5,
    'less than 4 hours': 3
}

df_psqi['Q4_numeric'] = df_psqi[q4_column].map(q4_numeric_mapping)

# Check results
print(df_psqi[[q4_column, 'C3']].head())

  4. How many hours of actual sleep do you get at night?  C3
0                                          7-8 hours       1
1                                  less than 4 hours       3
2                                  less than 4 hours       3
3                                          4-6 hours       2
4                                          4-6 hours       2

In [18]:
q5_column = psqi_related_columns[4]  # Index 4 in your PSQI columns list

# Let's check Q5 values
print(df_psqi[q5_column].unique())

['8-10 hours' 'more than 10 hours' '5-7 hours' 'less than 5 hours']

In [19]:
# Clean and standardize Q5 values
df_psqi[q5_column] = df_psqi[q5_column].str.strip().str.lower()

# Map Q5 (Hours in Bed) to numeric values
q5_numeric_mapping = {
    'more than 10 hours': 10.5,
    '8-10 hours': 9,
    '5-7 hours': 6,
    'less than 5 hours': 4
}

df_psqi['Q5_numeric'] = df_psqi[q5_column].map(q5_numeric_mapping)
# Check results
print(df_psqi[[q5_column, 'Q5_numeric']].head())

  5.  How many hours were you in bed?  Q5_numeric
0                          8-10 hours         9.0
1                  more than 10 hours        10.5
2                          8-10 hours         9.0
3                           5-7 hours         6.0
4                           5-7 hours         6.0

In [22]:
# Calculate sleep efficiency
df_psqi['efficiency'] = (df_psqi['Q4_numeric'] / df_psqi['Q5_numeric']) * 100
# Check results
print(df_psqi[['Q4_numeric', 'Q5_numeric', 'efficiency']].head())

   Q4_numeric  Q5_numeric  efficiency
0         7.5         9.0   83.333333
1         3.0        10.5   28.571429
2         3.0         9.0   33.333333
3         5.0         6.0   83.333333
4         5.0         6.0   83.333333

In [23]:
# Scoring Sleep Efficiency
def efficiency_score(eff):
    if eff > 85:
        return 0
    elif 75 <= eff <= 84:
        return 1
    elif 65 <= eff <= 74:
        return 2
    else:
        return 3

df_psqi['C4'] = df_psqi['efficiency'].apply(efficiency_score)

# Check results
print(df_psqi[['Q4_numeric', 'Q5_numeric', 'efficiency', 'C4']].head())

   Q4_numeric  Q5_numeric  efficiency  C4
0         7.5         9.0   83.333333   1
1         3.0        10.5   28.571429   3
2         3.0         9.0   33.333333   3
3         5.0         6.0   83.333333   1
4         5.0         6.0   83.333333   1

### Component 5 Sleep Disturbances.
 Questions Involved (Q7–Q15):
Waking up at night, bathroom use, snoring, temperature discomfort, bad dreams, pain, etc.

🎯 Scoring for Each Q7–Q15:
0 points → Not during the past month

1 point → Less than once a week

2 points → Once or twice a week

3 points → Three or more times a week

🔹 Component 5 Calculation:
Take sum of Q7–Q15 scores, then:

0 points → Sum = 0

1 point → Sum = 1–9

2 points → Sum = 10–18

3 points → Sum = 19+

In [30]:
# Q7–Q15 columns
disturbance_cols = psqi_related_columns[6:15]  # Index 6 to 14

# Clean values for Q7–Q15
df_psqi[disturbance_cols] = df_psqi[disturbance_cols].apply(lambda col: col.str.strip().str.lower())

# Define ordinal mapping for all disturbance questions
disturbance_mapping = {
    'not during last month': 0,
    'less then once a week': 1,
    'once or twice a week': 2,
    'three or more in week': 3
}
# ['not during last month' 'three or more in week' 'less then once a week'
#  'once or twice a week']
# Apply mapping
for col in disturbance_cols:
    df_psqi[col + '_score'] = df_psqi[col].map(disturbance_mapping)

# Sum the disturbance scores
disturbance_score_cols = [col + '_score' for col in disturbance_cols]
df_psqi['disturbance_sum'] = df_psqi[disturbance_score_cols].sum(axis=1)

In [31]:
# Component 5 scoring
def disturbance_component_score(total):
    if total == 0:
        return 0
    elif 1 <= total <= 9:
        return 1
    elif 10 <= total <= 18:
        return 2
    else:
        return 3

df_psqi['C5'] = df_psqi['disturbance_sum'].apply(disturbance_component_score)

# Check results
print(df_psqi[['disturbance_sum', 'C5']].head())

   disturbance_sum  C5
0                3   1
1               10   2
2               13   2
3                0   0
4                2   1

In [33]:
df_psqi.head(10)

,1. When I am usually gone to bed?,2. How long (in minutes) has it taken you to fall asleep each night?,3. When have you usually gotten up in the morning?,4. How many hours of actual sleep do you get at night?,5. How many hours were you in bed?,"6. In last 30 days, How many times, I cannot get to sleep within 30 minutes?","7. In last 30 days, How many times, I wake up in the middle of the night or early morning?","8. In last 30 days, How many times, I had to get up to use the bathroom?","9. In last 30 days, How many times, I cannot breathe comfortably?","10. In last 30 days, How many times, I cough or snore loudly?",...,"8. In last 30 days, How many times, I had to get up to use the bathroom?_score","9. In last 30 days, How many times, I cannot breathe comfortably?_score","10. In last 30 days, How many times, I cough or snore loudly?_score","11. In last 30 days, How many times, I feel too cold?_score","12. In last 30 days, How many times, I feel too hot?_score","13. In last 30 days, How many times, I saw bad dreams?_score","14. In last 30 days, How many times, I have pain during sleep?_score","15. In last 30 days, How many times, I having trouble sleeping for any other reason?_score",disturbance_sum,C5
0,12.01 AM to 2.00 AM,within 15 minutes,After 9.00 AM,7-8 hours,8-10 hours,once or twice a week,not during last month,less then once a week,not during last month,not during last month,...,1,0,0,1,0,0,0,1,3,1
1,10.01 PM to 12.00 AM,16-30,After 9.00 AM,less than 4 hours,more than 10 hours,three or more in week,not during last month,three or more in week,less then once a week,less then once a week,...,3,1,1,1,3,1,0,0,10,2
2,2.01 AM to 5.00 AM,31-60,7.01 AM to 9.00 AM,less than 4 hours,8-10 hours,three or more in week,three or more in week,less then once a week,less then once a week,not during last month,...,1,1,0,0,1,1,3,3,13,2
3,10.01 PM to 12.00 AM,within 15 minutes,5.01 AM to 7.00 AM,4-6 hours,5-7 hours,not during last month,not during last month,not during last month,not during last month,not during last month,...,0,0,0,0,0,0,0,0,0,0
4,2.01 AM to 5.00 AM,16-30,After 9.00 AM,4-6 hours,5-7 hours,not during last month,not during last month,not during last month,not during last month,not during last month,...,0,0,0,0,0,0,1,1,2,1
5,10.01 PM to 12.00 AM,16-30,5.01 AM to 7.00 AM,4-6 hours,8-10 hours,not during last month,less then once a week,less then once a week,less then once a week,not during last month,...,1,1,0,1,1,1,0,1,7,1
6,12.01 AM to 2.00 AM,16-30,5.01 AM to 7.00 AM,4-6 hours,5-7 hours,less then once a week,once or twice a week,less then once a week,less then once a week,less then once a week,...,1,1,1,1,1,0,0,0,7,1
7,12.01 AM to 2.00 AM,16-30,7.01 AM to 9.00 AM,4-6 hours,5-7 hours,not during last month,less then once a week,less then once a week,not during last month,less then once a week,...,1,0,1,2,0,0,0,0,5,1
8,12.01 AM to 2.00 AM,within 15 minutes,After 9.00 AM,more than 8 hours,8-10 hours,not during last month,less then once a week,less then once a week,not during last month,not during last month,...,1,0,0,3,0,0,0,0,5,1
9,12.01 AM to 2.00 AM,within 15 minutes,5.01 AM to 7.00 AM,4-6 hours,5-7 hours,not during last month,once or twice a week,not during last month,not during last month,not during last month,...,0,0,0,0,0,0,0,0,2,1

### Component6

 Component 6 (C6): Use of Sleeping Medication
🔹 Question:
Q16: "In the last 30 days, have you taken medicines for sleep?"

🎯 Scoring for Q16:
0 points → Not during the past month

1 point → Less than once a week

2 points → Once or twice a week

3 points → Three or more times a week

In [44]:
# Q16 column
q16_column = psqi_related_columns[15]  # Index 15 in your PSQI columns list

# Clean values
df_psqi[q16_column] = df_psqi[q16_column].str.strip().str.lower()

# Updated mapping for your Q16 values
medication_mapping_updated = {
    'not during last month': 0,
    'less then once a week': 1,
    'once or twice a week': 2,
    'three or more in week': 3
}

# Apply updated mapping
df_psqi['C6'] = df_psqi[q16_column].map(medication_mapping_updated)

# Check results
print(df_psqi[[q16_column, 'C6']].head())

  16. In last 30 days, In last month, have you take medicines for sleep?  C6
0                              not during last month                       0
1                              less then once a week                       1
2                              not during last month                       0
3                              not during last month                       0
4                              less then once a week                       1

['not during last month' 'less then once a week' 'once or twice a week'
 'three or more in week']

### Day Time Disfunctioning.
 Component 7 (C7): Daytime Dysfunction
🔹 Questions:
Q17: "In the last month, how many times you cannot sleep due to any program or other important case?"

Q18: "In the last month, how many times you face problems to maintain program or other important case?"

🎯 Scoring for Q17 & Q18:
0 points → Not during the past month

1 point → Less than once a week

2 points → Once or twice a week

3 points → Three or more times a week

🔹 Component 7 Logic:
Sum of Q17_score + Q18_score → Map to C7:

0 points → Sum = 0

1 point → Sum = 1–2

2 points → Sum = 3–4

3 points → Sum = 5–6

In [45]:
# Q17 & Q18 columns
q17_column = psqi_related_columns[16]
q18_column = psqi_related_columns[17]

# Clean values
df_psqi[q17_column] = df_psqi[q17_column].str.strip().str.lower()
df_psqi[q18_column] = df_psqi[q18_column].str.strip().str.lower()

# Let's check their unique values
print(df_psqi[q17_column].unique())
print(df_psqi[q18_column].unique())

['less then once a week' 'three or more in week' 'not during last month'
 'once or twice a week']
['less then once a week' 'once or twice a week' 'not during last month'
 'three or more in week']

In [46]:
# Define mapping
daytime_mapping = {
    'not during last month': 0,
    'less then once a week': 1,
    'once or twice a week': 2,
    'three or more in week': 3
}

# Map Q17 & Q18
df_psqi['Q17_score'] = df_psqi[q17_column].map(daytime_mapping)
df_psqi['Q18_score'] = df_psqi[q18_column].map(daytime_mapping)

# Sum for Component 7
df_psqi['daytime_sum'] = df_psqi['Q17_score'] + df_psqi['Q18_score']

In [47]:
# Component 7 scoring
def dysfunction_score(total):
    if total == 0:
        return 0
    elif 1 <= total <= 2:
        return 1
    elif 3 <= total <= 4:
        return 2
    else:
        return 3

df_psqi['C7'] = df_psqi['daytime_sum'].apply(dysfunction_score)

# Check results
print(df_psqi[['Q17_score', 'Q18_score', 'daytime_sum', 'C7']].head())

   Q17_score  Q18_score  daytime_sum  C7
0          1          1            2   1
1          1          1            2   1
2          3          2            5   3
3          0          0            0   0
4          1          1            2   1

In [51]:
# Correct the typos and map properly
subjective_quality_mapping_fixed = {
    'very good': 0,
    'farely good': 1,  # typo handled
    'fairly good': 1,
    'farely bad': 2,   # typo handled
    'fairly bad': 2,
    'very bad': 3
}

# Apply updated mapping
df_psqi['C1'] = df_psqi[q19_column].map(subjective_quality_mapping_fixed)

# Check result
print(df_psqi[[q19_column, 'C1']].head())

  19. During the past month, how would you rate your sleep quality overall?  \
0                                        farely good
1                                           very bad
2                                           very bad
3                                        farely good
4                                        farely good

   C1
0   1
1   3
2   3
3   1
4   1

In [50]:
df_psqi[q19_column].unique()

array(['farely good', 'very bad', 'very good', 'farely bad'], dtype=object)

Final Step: Total PSQI Score Calculation
🎯 PSQI Total Score:
Simply sum all 7 component scores:

PSQI_score
=
𝐶
1
+
𝐶
2
+
𝐶
3
+
𝐶
4
+
𝐶
5
+
𝐶
6
+
𝐶
7
PSQI_score=C1+C2+C3+C4+C5+C6+C7
Range: 0 (good sleep) → 21 (poor sleep)

In [52]:
# Make sure you have all components
component_columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']

# Final PSQI score
df_psqi['PSQI_score'] = df_psqi[component_columns].sum(axis=1)

# Check results
print(df_psqi[component_columns + ['PSQI_score']].head())

   C1  C2  C3  C4  C5  C6  C7  PSQI_score
0   1   1   1   1   1   0   1           6
1   3   0   3   3   2   1   1          13
2   3   0   3   3   2   0   3          14
3   1   0   2   1   0   0   0           4
4   1   0   2   1   1   1   1           7

In [ ]:
soci

In [54]:
social_df = pd.read_csv(r"E:\project_dv\paper1\social_df.csv")

In [57]:
social_df.head()

,SM_Q2_Platform_facebook,SM_Q2_Platform_imo,SM_Q2_Platform_instagram,SM_Q2_Platform_snapchat,SM_Q2_Platform_tiktok,SM_Q2_Platform_twitter,SM_Q2_Platform_wechat,SM_Q2_Platform_whatsapp,SM_Q3_Device_desktop,SM_Q3_Device_laptop,...,"11. In last 30 days, How many times, I feel too cold?","12. In last 30 days, How many times, I feel too hot?","13. In last 30 days, How many times, I saw bad dreams?","14. In last 30 days, How many times, I have pain during sleep?","15. In last 30 days, How many times, I having trouble sleeping for any other reason?","16. In last 30 days, In last month, have you take medicines for sleep?","17. In last month, how many times you cannot sleep due to any program or other important case?","18. In last month, how many times you face problems to maintain program or other important case?","19. During the past month, how would you rate your sleep quality overall?",PSQI_score
0,True,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
1,True,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,True,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
3,False,False,False,False,False,True,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,False,False,False,False,False,True,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7

In [58]:
social_df['PSQI_score'] = df_psqi['PSQI_score']
# Save the final DataFrame to a new Excel file 
social_df.to_csv(r"E:\project_dv\paper1\social_df.csv", index=False)